### ISSUE TITLE
Backend 젠킨스, 도커 설정

### ISSUE THREAD

**Issue by 2-one-week** [boostcamp-2020/IssueTracker-14#39]
Backend 젠킨스, 도커 설정

**Comment by ed-jinyoung-park** [comment]
Backend 브랜치가 merge될때마다 jenkins에서 docker image 재생성 및 배포

URL : http://115.85.183.106:3000/

* Docker 정리 : https://github.com/boostcamp-2020/IssueTracker-14/wiki/Docker
* Jenkins 정리 : https://github.com/boostcamp-2020/IssueTracker-14/wiki/Jenkins%EB%A1%9C-Docker-%EC%9E%90%EB%8F%99%EB%B0%B0%ED%8F%AC
